package com.neuedu.dao;

import com.neuedu.pojo.Order_item;
import java.util.List;

public interface Order_itemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newbee_order_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newbee_order_item
     *
     * @mbg.generated
     */
    int insert(Order_item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newbee_order_item
     *
     * @mbg.generated
     */
    Order_item selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newbee_order_item
     *
     * @mbg.generated
     */
    List<Order_item> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newbee_order_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order_item record);
}